//! TODO: docs.

extern crate alloc;

mod action;
mod action_name;
mod actor_id;
mod actor_map;
mod async_action;
mod autocmd;
pub mod autocmds;
mod boo;
pub mod buf_attach;
mod buffer_id;
mod byte_offset;
mod command;
mod command_args;
pub mod config;
pub mod ctx;
mod decoration_provider;
pub mod diagnostics;
mod event;
pub mod events;
mod executor;
mod function;
mod join_handle;
mod log;
mod maybe_result;
mod module;
mod module_api;
mod module_commands;
mod module_name;
mod nomad;
mod nomad_command;
mod point;
mod replacement;
mod serde;
mod shared;
mod text;

pub use action::{Action, FnAction};
pub use action_name::ActionName;
pub use actor_id::ActorId;
pub use async_action::AsyncAction;
pub use autocmd::{AutoCommand, ShouldDetach};
pub use boo::Boo;
pub use buffer_id::BufferId;
pub use byte_offset::ByteOffset;
pub use command::Command;
pub use command_args::CommandArgs;
pub use decoration_provider::Selection;
pub use event::Event;
pub use function::Function;
pub use join_handle::JoinHandle;
pub use module::Module;
pub use module_api::ModuleApi;
pub use module_name::ModuleName;
pub use nomad::Nomad;
pub use nomad_macros::{action_name, module_name};
pub use nvim_oxi;
pub use replacement::Replacement;
pub use shared::Shared;
pub use text::Text;
